export const ROOM_DETAILS = [
    {
        id: 1,
        roomName: "Apartment 1",
        image: "/images/room1.jpg",
        price: "$1500 per month",
        type: "Suite",
        occupancy: "2 Adults",
        amenities: ["WiFi", "Air Conditioning", "Private Bathroom", "Breakfast Included"],
    },
    {
        id: 2,
        roomName: "Apartment 2",
        image: "/images/room2.jpg",
        price: "$1000 per month",
        type: "Double",
        occupancy: "2 Adults",
        amenities: ["WiFi", "TV", "Private Bathroom"],
    },
    {
        id: 3,
        roomName: "Apartment 3",
        image: "/images/room3.jpg",
        price: "$750 per month",
        type: "Single",
        occupancy: "1 Adult",
        amenities: ["WiFi", "TV", "Shared Bathroom"],
    },
    {
        id: 4,
        roomName: "Apartment 4",
        image: "/images/room4.jpg",
        price: "$2000 per night",
        type: "Suite",
        occupancy: "4 Guests",
        amenities: ["WiFi", "Kitchen", "Private Bathroom", "Breakfast Included"],
    },
    {
        id: 5,
        roomName: "Apartment 5",
        image: "/images/room5.jpg",
        price: "$5000 per night",
        type: "Penthouse",
        occupancy: "6 Guests",
        amenities: ["WiFi", "Air Conditioning", "Jacuzzi", "Private Terrace"],
    },
    {
        id: 6,
        roomName: "Apartment 6",
        image: "/images/room6.jpg",
        price: "$3500 per night",
        type: "Villa",
        occupancy: "5 Guests",
        amenities: ["WiFi", "Kitchen", "Ocean View", "Private Pool"],
    },
    {
        id: 7,
        roomName: "Apartment 7",
        image: "/images/room7.jpg",
        price: "$1800 per night",
        type: "Business",
        occupancy: "1 Adult",
        amenities: ["WiFi", "Work Desk", "Private Bathroom", "Coffee Maker"],
    },
    {
        id: 8,
        roomName: "Apartment 8",
        image: "/images/room8.jpg",
        price: "$1200 per night",
        type: "Cabin",
        occupancy: "3 Guests",
        amenities: ["WiFi", "Fireplace", "Outdoor Seating"],
    },
    {
        id: 9,
        roomName: "Apartment 9",
        image: "/images/room9.jpg",
        price: "$40 per night",
        type: "Dormitory",
        occupancy: "1 Person per Bed",
        amenities: ["WiFi", "Shared Bathroom", "Locker Storage"],
    },
];
