export const ROOM_DETAILS = [
    {
        id: 1,
        roomName: "Deluxe King Suite",
        image: "/images/room1.jpg",
        price: "$150 per night",
        type: "Suite",
        occupancy: "2 Adults",
        amenities: ["WiFi", "Air Conditioning", "Private Bathroom", "Breakfast Included"],
    },
    {
        id: 2,
        roomName: "Standard Double Room",
        image: "/images/room2.jpg",
        price: "$100 per night",
        type: "Double",
        occupancy: "2 Adults",
        amenities: ["WiFi", "TV", "Private Bathroom"],
    },
    {
        id: 3,
        roomName: "Single Economy Room",
        image: "/images/room3.jpg",
        price: "$75 per night",
        type: "Single",
        occupancy: "1 Adult",
        amenities: ["WiFi", "TV", "Shared Bathroom"],
    },
    {
        id: 4,
        roomName: "Family Suite",
        image: "/images/room4.jpg",
        price: "$200 per night",
        type: "Suite",
        occupancy: "4 Guests",
        amenities: ["WiFi", "Kitchen", "Private Bathroom", "Breakfast Included"],
    },
    {
        id: 5,
        roomName: "Luxury Penthouse",
        image: "/images/room5.jpg",
        price: "$500 per night",
        type: "Penthouse",
        occupancy: "6 Guests",
        amenities: ["WiFi", "Air Conditioning", "Jacuzzi", "Private Terrace"],
    },
    {
        id: 6,
        roomName: "Beachfront Villa",
        image: "/images/room6.jpg",
        price: "$350 per night",
        type: "Villa",
        occupancy: "5 Guests",
        amenities: ["WiFi", "Kitchen", "Ocean View", "Private Pool"],
    },
    {
        id: 7,
        roomName: "Executive Business Room",
        image: "/images/room7.jpg",
        price: "$180 per night",
        type: "Business",
        occupancy: "1 Adult",
        amenities: ["WiFi", "Work Desk", "Private Bathroom", "Coffee Maker"],
    },
    {
        id: 8,
        roomName: "Rustic Cabin",
        image: "/images/room8.jpg",
        price: "$120 per night",
        type: "Cabin",
        occupancy: "3 Guests",
        amenities: ["WiFi", "Fireplace", "Outdoor Seating"],
    },
    {
        id: 9,
        roomName: "Dormitory Bunk Bed",
        image: "/images/room9.jpg",
        price: "$40 per night",
        type: "Dormitory",
        occupancy: "1 Person per Bed",
        amenities: ["WiFi", "Shared Bathroom", "Locker Storage"],
    },
];
